import glob
from itertools import combinations

configfile: "config.yaml"

DATA_DIR = config["data_dir"]
OUT_DIR = config["out_dir"]
RESULTS_DIR = config["results_dir"]
LOG_DIR = config["log_dir"]

SAMPLE_NAMES = config["samples"].keys()
SAMPLE_PAIRS = list(combinations(SAMPLE_NAMES, 2))


# rule barcode_concatenation:
#     input:
#         lambda wildcards: glob.glob(config["BARCODE_DIRECTORIES"][wildcards.barcode] + "/*")
#     output:
#         f"{OUT_DIR}/fastq/{{barcode}}.fastq.gz"
#     log:
#         f"{LOG_DIR}/cat/{{barcode}}.log"
#     shell:
#         """
#         cat {input} > {output} 2> {log}
#         """
#
# rule combining_samples:
#     input:
#         lambda wildcards: expand("data/fastq/{barcode}.fastq.gz", barcode=config["sample_barcodes"][wildcards.sample])
#     output:
#         f"{OUT_DIR}/combined_fastq/{{sample}}.fastq"
#     log:
#         f"{LOG_DIR}/combining_samples/{{sample}}.log"
#     shell:
#         """
#         cat {input} > {output} 2> {log}
#         """

include: "rules/fastq_qc_plong.smk"
include: "rules/kraken2_taxonomic_classification.smk"
include: "rules/bracken.smk"
include: "rules/krona_visualisation.smk"
include: "rules/kraken_biom.smk"
include: "rules/faprotax.smk"
include: "rules/generate_pathway_bubble_plot.smk"
include: "rules/generate_sankey.smk"
include: "rules/calculate_alpha_diversity.smk"
include: "rules/calculate_beta_diversity.smk"

rule all:
    input:
        alpha_diversity = expand(f"{RESULTS_DIR}/alpha/{{sample}}_alpha.txt",sample=SAMPLE_NAMES),
        beta_diversity = expand(
            f"{RESULTS_DIR}/beta/{{sample1}}_vs_{{sample2}}.txt",
            zip,
            sample1=[p[0] for p in SAMPLE_PAIRS],
            sample2=[p[1] for p in SAMPLE_PAIRS]
        ),
        sankey_plot = expand(f"{RESULTS_DIR}/sankey/{{sample}}.html",sample=SAMPLE_NAMES),
        pathway_bubble_plot = expand(f"{RESULTS_DIR}/pathway_bubble_plot/{{sample}}.pdf",sample=SAMPLE_NAMES),
        pathway_heatmap_pdf = expand(f"{RESULTS_DIR}/pathway_heatmap/{{sample}}_pathway_heatmap.pdf",sample=SAMPLE_NAMES),
        krona_vis = expand(f"{RESULTS_DIR}/krona/{{sample}}_krona.html",sample=SAMPLE_NAMES)
