configfile: "config.yaml"

SAMPLES = config["samples"]

include: "rules/generate_sankey.smk"
include: "rules/calculate_alpha_diversity.smk"

rule all:
    input:
    # QC with Fastplong:
        expand("trimmed/{sample}.fastq", sample=SAMPLES.keys()),
        expand("QC/{sample}_fastplong_QC.html", sample=SAMPLES.keys()),
        expand("logs/QC/{sample}.log", sample=SAMPLES.keys()),

    # kraken2:
        expand("kraken2/output/{sample}_output.txt", sample=SAMPLES.keys()),
        expand("kraken2/reports/{sample}_report.txt", sample=SAMPLES.keys()),
        expand("logs/kraken2/{sample}.log", sample=SAMPLES.keys()), 

    #Bracken
        expand("bracken/output/{sample}.out", sample=SAMPLES.keys()),
        expand("bracken/reports/{sample}.txt", sample=SAMPLES.keys()),
        expand("logs/bracken/{sample}.log", sample=SAMPLES.keys()), 

	# Krona
        expand("krona/{sample}_krona.html", sample=SAMPLES.keys()),
        expand("logs/krona/{sample}.log", sample=SAMPLES.keys()), 
    
    # kraken-biom
        expand("kraken_biom/{sample}_output.biom", sample=SAMPLES.keys()),
        expand("logs/kraken_biom/{sample}.log", sample=SAMPLES.keys()),

    #Faprotax
        expand("faprotax/{sample}/{sample}_function_table.tsv", sample=SAMPLES.keys()),
        expand("faprotax/{sample}/{sample}_report.txt", sample=SAMPLES.keys()),
        expand("faprotax/{sample}/group_table.txt", sample=SAMPLES.keys()),
        expand("faprotax/{sample}/sub_groups/", sample=SAMPLES.keys()),
        expand("logs/faprotax/{sample}.log", sample=SAMPLES.keys())

    # alpha diversity

    # beta diversity

    #sankey plot - bracken report
        expand("results/sankey/{sample}.html", sample=SAMPLES.keys())
        alpha_diversity=expand("results/alpha/{sample}_alpha.txt", sample=SAMPLES),

# Quality control and adapter trimming:
rule fastq_qc_plong:
    input:
        lambda wildcards: SAMPLES[wildcards.sample]
    output:
        fastq="trimmed/{sample}.fastq",
        html="QC/{sample}_fastplong_QC.html"
    log:
        "logs/QC/{sample}.log"
    shell:
        """
        tools/fastplong \
        -i {input} \
        -o {output.fastq} \
        -h {output.html} \
        2> {log}
        """

rule kraken2_taxonomic_classification:
    input:
        reads="trimmed/{sample}.fastq"
    output:
        kraken_report="kraken2/reports/{sample}_report.txt",
        output="kraken2/output/{sample}_output.txt"
    log:
        "logs/kraken2/{sample}.log"
    params:
        db="/data/datasets/KRAKEN2_INDEX/16S_Greengenes/",  
        confidence="0.1",               
        threads=128
    conda:
        "envs/kraken2.yaml"              
    shell:
        """
        kraken2 --db {params.db} \
                --threads {params.threads} \
                --confidence {params.confidence} \
                --output {output.output} \
                --report {output.kraken_report} \
                {input.reads} 2> {log}
        """

# For bracken, only genus level worked, not species level (https://github.com/jenniferlu717/Bracken/issues/117)

# threads nog erbij zetten
rule bracken:
    input:
        kraken_report = "kraken2/reports/{sample}_report.txt",
        kraken_database = "/data/datasets/KRAKEN2_INDEX/16S_Greengenes"
    output:
        bracken_report = "bracken/reports/{sample}.txt",
        bracken_output = "bracken/output/{sample}.out"
    params:
        read_length = 150,
        threshold = 10,
        level = "G"
    log: 
        "logs/bracken/{sample}.log"
    threads: 32
    conda:
        "envs/bracken.yaml" 
    shell:
        """
        bracken -d {input.kraken_database} \
                -i {input.kraken_report} \
                -o {output.bracken_output} \
                -w {output.bracken_report} \
                -r {params.read_length} \
                -t {params.threshold} \
                -l {params.level} \
                2> {log}
        """

rule krona_visualisation:
    input:
        bracken_files="bracken/reports/{sample}.txt"
    output: 
        krona_vis="krona/{sample}_krona.html"
    log:
        "logs/krona/{sample}.log"
    conda:
        "envs/krona.yaml"
    shell:
        """
        ktImportTaxonomy -t 5 \
                         -m 3 \
                         {input} \
                         -o {output} \
                         2> {log}
        """

rule kraken_biom:
    input:  
        bracken_kraken="bracken/reports/{sample}.txt"		
    output: 
        biom_files="kraken_biom/{sample}_output.biom"
    log:
        "logs/kraken_biom/{sample}.log"
    conda:
        "envs/kraken_biom.yaml"
    shell:
        """
        kraken-biom {input} \
                    -o {output} \
                    --fmt json \
                    2> {log}
        """

rule faprotax:
    input:
        biom_files="kraken_biom/{sample}_output.biom"
    output:
        function_table="faprotax/{sample}/{sample}_function_table.tsv",
        faprotax_report="faprotax/{sample}/{sample}_report.txt",
        sub_table_dir=directory("faprotax/{sample}/sub_groups/"),
        groups_to_records="faprotax/{sample}/group_table.txt"
    log:
        "logs/faprotax/{sample}.log"
    shell:
        """
        python3 tools/FAPROTAX_1.2.10/collapse_table.py \
        -i {input.biom_files} \
        -o {output.function_table} \
        -g tools/FAPROTAX_1.2.10/FAPROTAX.txt \
        -n columns_after_collapsing \
        --collapse_by_metadata "taxonomy" \
        --out_sub_tables_dir {output.sub_table_dir} \
        --out_groups2records_table {output.groups_to_records} \
        --out_report {output.faprotax_report} \
        -v \
        2> {log}
        """


# To-do: Use seperate environments for all rules...(base)


# Om de fastq bestanden te combineren voor de analyze met kurona.
# To-do: directories als input geven om deze bestanden te genereren.
# rule kurona_preprocessing:
#     input:
#         lambda wildcards: config["BARCODE_DIRECTORIES"][wildcards.barcode]
#     output: 
#     "{barcode}_kurona.fastq"

#     shell: 
#         "cat {input}/*.fastq > {output}"


