samples:
    digester: data/digester.fastq.gz
    in_lagoon: data/in_lagoon.fastq.gz
    out_lagoon: data/out_lagoon.fastq.gz


KRAKEN_DB:
    16S_Greengenes: /data/datasets/KRAKEN2_INDEX/16S_Greengenes
    16S_RDP: /data/datasets/KRAKEN2_INDEX/16S_RDP
    16S_Silva: /data/datasets/KRAKEN2_INDEX/16S_Silva
    k2_core_nt: /data/datasets/KRAKEN2_INDEX/k2_core_nt
    k2_pluspf: /data/datasets/KRAKEN2_INDEX/k2_pluspf
    k2_pluspfp: /data/datasets/KRAKEN2_INDEX/k2_pluspfp
    k2_standard: /data/datasets/KRAKEN2_INDEX/k2_standard

GENOMES:
    ["hg38_refgenome"] # Human ref genome.


BARCODE_DIRECTORIES:
    barcode01: /commons/Themas/Thema07/metagenomics/ACFC_afvalwater/20250207_1125_MN35459_FAX73268_e839126d/fastq_pass/barcode01
    barcode02: /commons/Themas/Thema07/metagenomics/ACFC_afvalwater/20250207_1125_MN35459_FAX73268_e839126d/fastq_pass/barcode02
    barcode03: /commons/Themas/Thema07/metagenomics/ACFC_afvalwater/20250207_1125_MN35459_FAX73268_e839126d/fastq_pass/barcode03
    barcode04: /commons/Themas/Thema07/metagenomics/ACFC_afvalwater/20250207_1125_MN35459_FAX73268_e839126d/fastq_pass/barcode04
    barcode05: /commons/Themas/Thema07/metagenomics/ACFC_afvalwater/20250207_1125_MN35459_FAX73268_e839126d/fastq_pass/barcode05
    barcode06: /commons/Themas/Thema07/metagenomics/ACFC_afvalwater/20250207_1125_MN35459_FAX73268_e839126d/fastq_pass/barcode06
    barcode07: /commons/Themas/Thema07/metagenomics/ACFC_afvalwater/20250207_1125_MN35459_FAX73268_e839126d/fastq_pass/barcode07
    barcode08: /commons/Themas/Thema07/metagenomics/ACFC_afvalwater/20250207_1125_MN35459_FAX73268_e839126d/fastq_pass/barcode08
    barcode09: /commons/Themas/Thema07/metagenomics/ACFC_afvalwater/20250207_1125_MN35459_FAX73268_e839126d/fastq_pass/barcode09
    barcode10: /commons/Themas/Thema07/metagenomics/ACFC_afvalwater/20250207_1125_MN35459_FAX73268_e839126d/fastq_pass/barcode10
    barcode11: /commons/Themas/Thema07/metagenomics/ACFC_afvalwater/20250207_1125_MN35459_FAX73268_e839126d/fastq_pass/barcode11

